version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:5000
    environment:
      - DB_HOST=chitchat-db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=chitchat
      - REDIS_HOST=chitchat-redis
      - REDIS_PORT=6379
    networks:
      - app_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: chitchat-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chitchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  redis:
    image: redis:7
    container_name: chitchat-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: